### ISSUE TITLE
static_comments plugin no longer working with Jekyll v2. Why?

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-help#36]
Hello,

I’m currently rebuilding my site with Jekyll. I’ve retained the comments that were posted on my previous Movable Type-powered website (using the Movable Type import script) and the static_comments.rb plugin, found here: https://github.com/shigeya/jekyll-static-comments/

This was working _perfectly_ up until v1.5.1, but since the update to v2.0.x, I get the following error (using --trace): 

```
Pinova:paulrobertlloyd.dev paulrobertlloyd$ jekyll build --trace
Configuration file: /Users/paulrobertlloyd/Sites/paulrobertlloyd.dev/_config.yml
            Source: /Users/paulrobertlloyd/Sites/paulrobertlloyd.dev
       Destination: /Users/paulrobertlloyd/Sites/paulrobertlloyd.dev/_site
      Generating... 
  Liquid Exception: undefined local variable or method `relative_path' for #<StaticComments::StaticComment:0x007f877c1ee3c0> in _includes/sections/comments.html, included in _layouts/post.html
/Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/tags/include.rb:114:in `rescue in render': undefined local variable or method `relative_path' for #<StaticComments::StaticComment:0x007f877c1ee3c0> (Jekyll::Tags::IncludeTagError)
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/tags/include.rb:106:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:106:in `block in render_all'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `render_all'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/tags/if.rb:40:in `block (2 levels) in render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/tags/if.rb:38:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/tags/if.rb:38:in `block in render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/context.rb:105:in `stack'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/tags/if.rb:37:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:106:in `block in render_all'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:93:in `render_all'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/block.rb:82:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/template.rb:124:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/liquid-2.5.5/lib/liquid/template.rb:132:in `render!'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/convertible.rb:96:in `render_liquid'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/convertible.rb:142:in `render_all_layouts'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/convertible.rb:176:in `do_layout'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/post.rb:266:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/site.rb:245:in `block in render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/site.rb:244:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/site.rb:244:in `render'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/site.rb:43:in `process'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/command.rb:43:in `process_site'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/commands/build.rb:46:in `build'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/commands/build.rb:30:in `process'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `call'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `each'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary/command.rb:220:in `execute'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary/program.rb:35:in `go'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/mercenary-0.3.3/lib/mercenary.rb:22:in `program'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/gems/jekyll-2.0.2/bin/jekyll:18:in `<top (required)>'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/bin/jekyll:23:in `load'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/bin/jekyll:23:in `<main>'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/paulrobertlloyd/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

My source code is available here: https://github.com/paulrobertlloyd/paulrobertlloyd.com 

_(Note that comments are not available on my GitHub repo as they contain user’s email addresses. However, there is a folder called _comments in the root of the project, which contains a folder for each post with comments, and a .markdown file for each comment.)_

What has changed in v2.0 that would cause this issue?

Thanks,

Paul
